Testing branch
Redvanisation/tic-tac-toe-ruby pull request #10
Opened 2019-07-22 02:25 UTC by Redvanisation

2019-07-22 03:08 UTC, maelfosso commented
# Reviews in progress by Mael FOSSO

2019-07-22 03:40 UTC, maelfosso commented on spec/game_spec.rb
> +            expect(board.full?).to eq(true)
You're testing the **Game** class, not the **Board** one. 
So I think you should rather have
`expect(game.check_draw).to eq(true)`

2019-07-22 13:35 UTC, mcrd25 commented
# This project is currently being reviewed by TSE [Maya Douglas](@mcrd25)

2019-07-22 14:20 UTC, mcrd25 requested changes
# Wow! the project looks neat! Really good job! Almost time for blast off 🚀 

Hi, @Redvanisation  and @VihoSerge 👋,

Hope all is well, you've done a good job, however, I am wondering why @Redvanisation  has 26 of the 29 commits while @VihoSerge  only has 3. I'm sure there is a reasonable explanation for this 😅 

Please also request re-review for this project under Ruby Testing not OOP.

You guys have done a great job, however not all requirements to pass have been met, mainly because not all of your public methods have been tested 😢.

**SEE CHECKLIST BELOW**

# Minimum Requirements Checklist

To consider the project 'complete' it must satisfy the following points:

### Project Specification 

- [x] All the public methods of the classes implemented in project OOP are tested
- [x] Check if specs are passing on your machine.
- [x] Check if specs are failing if you break some code in tested class.

### Crucial things to make project works

- [x] The project should be done solo or collaboratively and that the commit history reflects
- [x] The project has a descriptive README.md

- [x] code is clean: indentation with two spaces, line lengths, spaces around operators 
- [x] Ensure that students work with Git Flow: production `master` branch + main `develop` branch + Pull Requests from feature branches to the `develop`
- [x] Specs cover positive and negative scenarios 
      Example: there is a spec for correct usage of method [e.g. “it “creates object if all required attributes are passed”] 
      and also there is spec for wrong usage of method  [e.g. “it “does not create object if required attributes are missing”]. 
*For most part you've passed this except for that one method in your game class 😢*
- [x] Specs for each method should be wrapped in one `describe` block. 
- [x] You should have one `it` block for each expected behaviour.
- [x] Instead of using `before_each` to define a variable for the test cases, students should [Use `let` instead](https://github.com/rubocop-hq/rspec-style-guide#let-blocks).

I am really impressed with your projects. If you need any ideas of how to test your untested methods feel free to contact me.

***If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media.***

*Happy coding 😄,*
**[--Maya](https://github.com/mcrd25)**
[GitHub](https://github.com/mcrd25) [Twitter](https://twitter.com/mcrd25) [linkedin](https://www.linkedin.com/in/mayadouglas/)

2019-07-22 14:20 UTC, mcrd25 commented on .rspec
> +--format documentation
👍

2019-07-22 14:20 UTC, mcrd25 commented on spec/game_spec.rb
> +            expect(game.check_draw).to eq(true)
This test checks for a positive scenario, but you also should have a test that checks when you expect draw to equal false

2019-07-22 14:20 UTC, mcrd25 commented on spec/game_spec.rb
> +    describe "#check_victory" do
Great job implementing for negative and positive scenario!

2019-07-22 14:20 UTC, mcrd25 commented on spec/game_spec.rb
> +    describe "#check_game_over" do
Again, good job!

2019-07-23 17:02 UTC, maelfosso commented
# Under review by Mael FOSSO

2019-07-23 17:13 UTC, JamesOkunlade approved these changes
Great job with the testing project.

Your work is good and meets all basic requirement.

It's high time you moved on to another one. Good luck with your future projects. :+1:

2019-07-23 17:14 UTC, Redvanisation commented
Thanks for the reviews!

2019-07-23 17:16 UTC, merged